#!/bin/sh
# ----------------------------------------------------- #
#                                                       #
#                     BSPWM CONFIG                      #                     
#                                                       #                        
# ----------------------------------------------------- #
#--AutoStart--# {{{
#xrdb ~/.Xresources &
killall "picom"
killall polybar
killall flameshot
picom --experimental-backends &
feh --bg-scale --no-fehbg ~/Pictures/Backgrounds/forest.png &
flameshot &
$HOME/.config/polybar/launch.sh
# }}}
#--Monitors--# {{{
bspc monitor eDP-1-1 -d 1 2 3 4 5 6 7 
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 
#bspc monitor HDMI-0 -d I II III IV V VI VII
bspc monitor HDMI-0 -d I V X L C D M
# 一, 二, 三, 四, 五, 六, 七 
# }}}
#--Globals--# {{{
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config pointer_follows_focus false
bspc config focus_follows_pointer true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# borders
#bspc config normal_border_color "#4c566a"
#bspc config active_border_color "#1e1e1e"
#bspc config focused_border_color "#453175"
#bspc config presel_feedback_color "#5e81ac"
#bspc config urgent_border_color "#dd2727"

bspc config normal_border_color "#453175"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#b03356"  #"#ab153f"
#bspc config presel_feedback_color "#5e81ac"
# }}}
#--Monitor and Desktop Settings--# {{{
bspc config border_width    0 
#bspc config -m DP-2 window_gap      12
bspc config -m eDP-1-1 window_gap      12
bspc config -m eDP-1   window_gap      4
bspc config -m HDMI-0  window_gap      0
# Mon 1 {{{ 
bspc config -m eDP-1-1 top_padding 30
bspc config -m eDP-1-1 bottom_padding 2.5
bspc config -m eDP-1-1 left_padding  2.5
bspc config -m eDP-1-1 right_padding 2.5
bspc config -m eDP-1   top_padding    30
bspc config -m eDP-1   bottom_padding 0
bspc config -m eDP-1   left_padding   0
bspc config -m eDP-1   right_padding  0
# }}}
# Mon 2 {{{
bspc config -m HDMI-0 top_padding 0 #-15
bspc config -m HDMI-0 bottom_padding 0 #-15
bspc config -m HDMI-0 left_padding 0 #-15
bspc config -m HDMI-0 right_padding 0 #-14
# }}}
# }}}
# -- BSCP Config -- {{{
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# }}}
# -- BSPC Rules -- {{{
bspc rule -a scrcpy state=floating
bspc rule -a discord border=off
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a osmo state=floating
# }}}
# ----------------------------------------------------- #
