#!/bin/sh

STATUS=$(optimus-manager --status | grep "Current GPU mode : " | awk '{print $5}')

case $STATUS in
    nvidia)
        optimus-manager --switch intel --no-confirm
        killall xinit
        ;;
    intel)
        optimus-manager --switch nvidia --no-confirm
        killall xinit
        ;;
esac
