#!/bin/sh

STATUS=$(optimus-manager --status | grep "Current GPU mode : " | awk '{print $5}')

case $STATUS in
    nvidia)
        optimus-manager --switch intel --no-confirm
        bspc quit
        ;;
    intel)
        optimus-manager --switch nvidia --no-confirm
        bspc quit
        ;;
esac
